// Package users owns RunMitra's user accounts. RunMitra is now STANDALONE — it
// is the source of truth for identity, so this table holds the full runner
// profile and the bcrypt password hash. (Earlier it was a thin cache of
// MarathonMitra; that dependency is gone.)
package users

import (
	"context"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// User is a runner's account and profile. PasswordHash is tagged json:"-" so it
// is never serialized into a response. ID is a UUID stored as text (generated by
// the database) — every other table keys off this id.
type User struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	Phone        string    `json:"phone"`
	PasswordHash string    `json:"-"`
	Age          *int      `json:"age,omitempty"`
	TshirtSize   *string   `json:"tshirt_size,omitempty"`
	City         *string   `json:"city,omitempty"`
	ProfilePhoto *string   `json:"profile_photo,omitempty"`
	IsVerified   bool      `json:"is_verified"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// NewUser carries the fields needed to create an account. Optional profile fields
// are pointers so "not provided" is distinct from a zero value.
type NewUser struct {
	Name         string
	Email        string
	Phone        string
	PasswordHash string
	Age          *int
	TshirtSize   *string
	City         *string
}

// ErrNotFound is returned when no (non-deleted) user exists for a lookup.
var ErrNotFound = errors.New("user not found")

// ErrEmailTaken / ErrPhoneTaken surface unique-constraint violations so the auth
// layer can turn them into clear 409s instead of a generic 500.
var (
	ErrEmailTaken = errors.New("email already registered")
	ErrPhoneTaken = errors.New("phone already registered")
)

// Repository is the data-access layer for user accounts.
type Repository struct {
	db *pgxpool.Pool
}

// NewRepository wires the repository to a connection pool.
func NewRepository(db *pgxpool.Pool) *Repository {
	return &Repository{db: db}
}

// Create inserts a new account and returns it. The database generates the id
// (gen_random_uuid()::text) so callers never mint ids themselves.
func (r *Repository) Create(ctx context.Context, n NewUser) (*User, error) {
	const q = `
		INSERT INTO users (id, name, email, phone, password_hash, age, tshirt_size, city)
		VALUES (gen_random_uuid()::text, $1, $2, $3, $4, $5, $6, $7)
		RETURNING id, name, email, COALESCE(phone, ''), password_hash,
		          age, tshirt_size, city, profile_photo, is_verified,
		          created_at, updated_at`
	var u User
	err := r.db.QueryRow(ctx, q,
		n.Name, n.Email, nullable(n.Phone), n.PasswordHash, n.Age, n.TshirtSize, n.City,
	).Scan(
		&u.ID, &u.Name, &u.Email, &u.Phone, &u.PasswordHash,
		&u.Age, &u.TshirtSize, &u.City, &u.ProfilePhoto, &u.IsVerified,
		&u.CreatedAt, &u.UpdatedAt,
	)
	if err != nil {
		return nil, mapUniqueViolation(err)
	}
	return &u, nil
}

// GetByEmail looks up an account by email (case-insensitive via citext), used at
// login. The returned User includes PasswordHash so the service can verify it.
func (r *Repository) GetByEmail(ctx context.Context, email string) (*User, error) {
	const q = `
		SELECT id, name, email, COALESCE(phone, ''), password_hash,
		       age, tshirt_size, city, profile_photo, is_verified,
		       created_at, updated_at
		FROM users
		WHERE email = $1 AND deleted_at IS NULL`
	return r.scanOne(ctx, q, email)
}

// GetByID looks up an account by id (used by /users/me).
func (r *Repository) GetByID(ctx context.Context, id string) (*User, error) {
	const q = `
		SELECT id, name, email, COALESCE(phone, ''), password_hash,
		       age, tshirt_size, city, profile_photo, is_verified,
		       created_at, updated_at
		FROM users
		WHERE id = $1 AND deleted_at IS NULL`
	return r.scanOne(ctx, q, id)
}

// DisplayNames resolves many user ids to their names in one query — used by the
// leaderboard to label ranked users without an N+1 of GetByID calls.
func (r *Repository) DisplayNames(ctx context.Context, ids []string) (map[string]string, error) {
	out := make(map[string]string, len(ids))
	if len(ids) == 0 {
		return out, nil
	}
	const q = `SELECT id, name FROM users WHERE id = ANY($1)`
	rows, err := r.db.Query(ctx, q, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	for rows.Next() {
		var id, name string
		if err := rows.Scan(&id, &name); err != nil {
			return nil, err
		}
		out[id] = name
	}
	return out, rows.Err()
}

// scanOne runs a single-row profile query and maps "no rows" to ErrNotFound.
func (r *Repository) scanOne(ctx context.Context, q string, arg any) (*User, error) {
	var u User
	err := r.db.QueryRow(ctx, q, arg).Scan(
		&u.ID, &u.Name, &u.Email, &u.Phone, &u.PasswordHash,
		&u.Age, &u.TshirtSize, &u.City, &u.ProfilePhoto, &u.IsVerified,
		&u.CreatedAt, &u.UpdatedAt,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return &u, nil
}

// nullable turns an empty string into a nil so it lands as SQL NULL (keeps the
// partial unique index on phone happy for accounts without a number).
func nullable(s string) any {
	if s == "" {
		return nil
	}
	return s
}
